# throw文を使って独自の例外をスローする
プログラムの実行中にエラーが発生すると例外がスローされますが、 throw 文を使用すると任意のタイミングで例外をスローすることができます。

## throw文の使い方
throw 文を使用すると例外をスローすることができます。
書式は次のとおりです。

### throw 例外の値

例外の値には通常 Error オブジェクトを指定しますが、数値や文字列といった任意の値を指定することもできます。 
try...catch 文を使って例外がキャッチされた場合、ここで指定した例外の値が catch の括弧の中に記述した変数に格納されます。

関数内で引数として渡されてきた値をチェックし、 50 未満だった場合には例外をスローしています。
今回は例外の値として文字列を指定しています。スローされた例外は try...catch 文でキャッチされて、 catch ブロックの中に記述された処理が実行されます。